theme: jekyll-theme-cayman
title: Nicole and Chaithra's Final Project
description: Understanding the Equity Impacts of BART’s Transit Oriented Development Projects in Alameda County: Ethnicity and Rent Burden Analysis
